### ISSUE TITLE
Allow multiple salt state directories to be supplied for masterless minions

### ISSUE THREAD

**Issue by mikeywaites** [vmware-archive/salty-vagrant#15]
So previously when provisioning with puppet my set allowed for devs to maintain a set of their own manifests containing vim configs, bashrc setting etc.  The way i achieved this was setting a predifined set of dirs in the host in the vagrant file and mounting each of those onto the guest like so

```
config.vm.share_folder("common-dev", "/home/vagrant/modules/dev", "../../../modules/dev")

puppet.options = ["--modulepath", "some/paths"]

```

it would be great to be able to replicate this functionality with salt!!  in the mean time even a work around with the minion.conf file would be greatly appreciated if anyone knows of one!

**Comment by thatch45** [comment]
Yes, you can do this with directory overlays and environments in the file_roots option:
http://docs.saltstack.org/en/latest/ref/configuration/master.html#file-roots

**Comment by akoumjian** [comment]
@thatch45 thanks, I was looking for the link right now. This is already possible. You include the folders you want to mount in your Vagrantfile and then just reference those as separate file_roots or just reference those folders inside your state tree(s).

**Comment by thatch45** [comment]
yep :)

**Comment by mikeywaites** [comment]
Brilliant Utah_Dave pointed me in the direction after I made this request. Do you think this may be possible at some directly from the salty vagrant api?

**Comment by mikeywaites** [comment]
Hey again guys! finnally got round to giving this a whirl. so my base env in the minion conf looks something like 

``` yaml
base:
  - /path/to/mounted/dir
  - /path/to/another/mounted/dir
```

this first path in the base env is actually the one set in the vagrant file and seems to be the only states that actually get run.

```
salt.salt_file_root_path = '/path/to/mounted/dir'
```

I have a state defined in my top.sls file that is part of the second path that gets mounted by vagrant called dev.  This one dosent seem to run.  Is the salt provisioner ignoring the paths set in the minion.conf when running with vagrant?

#top.sls (which is included in the mounted dir specified with the file_root option

``` yaml
#base environment                                                                                                                                                                                                    
base:                                                                                                                                                                                                                
  '*':                                                                                                                                                                                                               
    - dev  # this is part of the second path mounted by vagrant defined in the minion.conf                                                                                                                                                                                                                                                                                                                                                                                                                  
    - redis                                                                                                                                                                                                          
  'web':                                                                                                                                                                                                             
    - nginx                                                                                                                                                                                                          
    - python                                                                                                                                                                                                         
```

again still getting used to salt but i would have expected salt to error out if a state was defined in the top.sls that i couldnt find? i just wanna check im on the right path and wether the problem lies in some misconfiguration or this is a bug.
